# Generated by Django 4.2.7 on 2026-02-25 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("morning", "Morning Shift"),
                            ("night", "Night Shift"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "punch_in_start",
                    models.TimeField(help_text="Earliest punch in time"),
                ),
                (
                    "punch_in_end",
                    models.TimeField(
                        help_text="Latest punch in time (after this = Late)"
                    ),
                ),
                (
                    "punch_out_time",
                    models.TimeField(help_text="Expected punch out time"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned shift",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="attendance_app.shift",
            ),
        ),
    ]
