# Generated by Django 4.2.7 on 2026-02-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_app", "0003_weekoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Holiday name (e.g., Republic Day, Diwali)",
                        max_length=200,
                    ),
                ),
                ("start_date", models.DateField(help_text="Holiday start date")),
                (
                    "end_date",
                    models.DateField(
                        help_text="Holiday end date (same as start for single day)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this holiday active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "ordering": ["-start_date"],
            },
        ),
    ]
